// Package swagger GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/packed-logs/upload-events": {
            "get": {
                "description": "查看日志通知记录",
                "tags": [
                    "日志通知相关接口"
                ],
                "summary": "查看日志通知记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page no",
                        "name": "page_no",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "int64"
                        }
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                }
            },
            "post": {
                "description": "通知去APP端下载日志，然后处理日志存储到数据库与S3",
                "tags": [
                    "日志通知相关接口"
                ],
                "summary": "被通知去APP端下载日志，然后处理日志存储到数据库与S3",
                "parameters": [
                    {
                        "type": "string",
                        "description": "消息唯一标识, 保证消息可靠性和业务幂等性，由客户端生成（保证唯一即可）",
                        "name": "msg_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "日志包的地址",
                        "name": "s3_url",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
